// Top 50 coins based on market cap as of Dec 22, 2021.
export const supportedCoins = [
  'bitcoin',
  'ethereum',
  'binancecoin',
  'tether',
  'solana',
  'ripple',
  'cardano',
  'usd-coin',
  'terra-luna',
  'polkadot',
  'avalanche-2',
  'dogecoin',
  'shiba-inu',
  'matic-network',
  'binance-usd',
  'crypto-com-chain',
  'wrapped-bitcoin',
  'litecoin',
  'terrausd',
  'chainlink',
  'dai',
  'algorand',
  'okb',
  'bitcoin-cash',
  'tron',
  'cosmos',
  'uniswap',
  'stellar',
  'axie-infinity',
  'near',
  'staked-ether',
  'hedera-hashgraph',
  'compound-ether',
  'vechain',
  'ftx-token',
  'filecoin',
  'elrond-erd-2',
  'ethereum-classic',
  'the-sandbox',
  'magic-internet-money',
  'theta-token',
  'internet-computer',
  'decentraland',
  'cdai',
  'fantom',
  'helium',
  'tezos',
  'the-graph',
  'iota',
  'compound-usd-coin',
] as const

export const coinGeckoBaseURL = 'https://api.coingecko.com/api/v3'

export const signatureText =
  "Sign in to Curious Addys' Virtual Trading Platform as "

export const accountCookieName = 'catc_itp_account'
